/**
 * Investigation Report — low-level jsPDF drawing helpers (Sprint 5.2).
 *
 * Every render function in `pdfSections.ts` is built from these primitives
 * instead of calling `doc.text`/`doc.rect`/`autoTable` directly with
 * repeated inline styling — this is the "extract repeated drawing helpers,
 * no duplicated layout code" half of this sprint's code-quality
 * requirement. Nothing here knows about `ReportData`; it only knows how to
 * put pixels on a jsPDF page.
 */
import { jsPDF } from "jspdf";
import autoTable, { type CellHookData, type UserOptions } from "jspdf-autotable";

import { APP_BRAND, REPORT_TITLE_SHORT, THEME, type RgbColor } from "./pdfTheme";

export const MARGIN = 40;

/** Y position where section content begins on every non-cover page — leaves
 * room above for `drawPageHeader`'s brand/case-filename strip + divider. */
export const CONTENT_START_Y = 74;

export function pageSize(doc: jsPDF): { width: number; height: number } {
  return { width: doc.internal.pageSize.getWidth(), height: doc.internal.pageSize.getHeight() };
}

/** `lastAutoTable.finalY` is set by jspdf-autotable at runtime but isn't part
 * of its (or jsPDF's) official type declarations, so it's narrowed through
 * `unknown` rather than reached with `any`. */
export function getFinalY(doc: jsPDF, fallback: number): number {
  const withTable = doc as unknown as { lastAutoTable?: { finalY: number } };
  return withTable.lastAutoTable?.finalY ?? fallback;
}

/** Thin wrappers around jsPDF's 3-arg color setters so callers can pass one
 * `RgbColor` tuple instead of spreading it out at every call site — used
 * throughout this file and re-exported for `pdfSections.ts` to share. */
export function fill(doc: jsPDF, color: RgbColor): void {
  doc.setFillColor(color[0], color[1], color[2]);
}
export function ink(doc: jsPDF, color: RgbColor): void {
  doc.setTextColor(color[0], color[1], color[2]);
}
export function stroke(doc: jsPDF, color: RgbColor): void {
  doc.setDrawColor(color[0], color[1], color[2]);
}

/** Resets text color/font back to the report's default body style. Called
 * at the end of most drawing helpers so one section's styling never bleeds
 * into the next. */
export function resetTextStyle(doc: jsPDF): void {
  ink(doc, THEME.text);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
}

/**
 * Small brand strip drawn at the top of every page except the cover:
 * "DFIR Workbench" (left) / case filename (right), the report subtitle
 * below, then a thin divider — see this sprint's Page Header requirement.
 */
export function drawPageHeader(doc: jsPDF, caseFilename: string): void {
  const { width } = pageSize(doc);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  ink(doc, THEME.text);
  doc.text(APP_BRAND, MARGIN, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  ink(doc, THEME.muted);
  doc.text(caseFilename, width - MARGIN, 28, { align: "right" });

  doc.setFontSize(8);
  doc.text(REPORT_TITLE_SHORT, MARGIN, 40);

  stroke(doc, THEME.border);
  doc.setLineWidth(0.75);
  doc.line(MARGIN, 48, width - MARGIN, 48);

  resetTextStyle(doc);
}

/** "Generated by DFIR Workbench" / "Page X of Y" — drawn on every page,
 * including the cover, per this sprint's Page Footer requirement. */
export function drawPageFooter(doc: jsPDF, page: number, totalPages: number): void {
  const { width, height } = pageSize(doc);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  ink(doc, THEME.muted);
  doc.text(`Generated by ${APP_BRAND}`, MARGIN, height - 24);
  doc.text(`Page ${page} of ${totalPages}`, width - MARGIN, height - 24, { align: "right" });
  resetTextStyle(doc);
}

/** Big blue section title + underline, e.g. "Case Information". Returns the
 * y position content should start at below it. */
export function drawSectionHeading(doc: jsPDF, title: string): number {
  const y = CONTENT_START_Y;
  ink(doc, THEME.primary);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, MARGIN, y);
  stroke(doc, THEME.primary);
  doc.setLineWidth(1.4);
  doc.line(MARGIN, y + 8, pageSize(doc).width - MARGIN, y + 8);
  resetTextStyle(doc);
  return y + 32;
}

/** Medium-weight subsection heading used inside a section, e.g. "Overview"
 * within Executive Summary — one step down from `drawSectionHeading` in
 * this report's typographic hierarchy. */
export function drawSubheading(doc: jsPDF, title: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  ink(doc, THEME.text);
  doc.text(title, MARGIN, y);
  resetTextStyle(doc);
  return y + 16;
}

/** Muted, small metadata line, e.g. "Last edited Aug 1, 2026 12:00:00". */
export function drawMeta(doc: jsPDF, text: string, x: number, y: number): void {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  ink(doc, THEME.muted);
  doc.text(text, x, y);
  resetTextStyle(doc);
}

export function drawEmptyState(doc: jsPDF, y: number, message: string): number {
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  ink(doc, THEME.muted);
  doc.text(message, MARGIN, y);
  resetTextStyle(doc);
  return y + 20;
}

/** Wraps `text` to `maxWidth` starting at `(x, y)` and returns the y
 * position immediately below the wrapped block, so callers can chain
 * paragraphs without re-deriving line counts by hand. */
export function drawParagraph(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 13,
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

/** Bulleted list, one wrapped paragraph per item. */
export function drawBulletList(
  doc: jsPDF,
  items: readonly string[],
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 13,
): number {
  let cursor = y;
  for (const item of items) {
    cursor = drawParagraph(doc, `•  ${item}`, x, cursor, maxWidth, lineHeight) + 4;
  }
  return cursor;
}

/** Small filled, rounded "pill" with centered white text — used for risk
 * levels and severity/level badges wherever a plain colored text label
 * would otherwise be shown, per this sprint's Color Coding requirement.
 * Returns the chip's width so standalone callers (cover page, conclusion)
 * can lay out around it. */
export function drawBadgeChip(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  color: RgbColor,
  align: "left" | "center" = "left",
): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  const paddingX = 7;
  const textWidth = doc.getTextWidth(text);
  const chipWidth = textWidth + paddingX * 2;
  const chipHeight = 15;
  const chipX = align === "center" ? x - chipWidth / 2 : x;

  fill(doc, color);
  doc.roundedRect(chipX, y, chipWidth, chipHeight, 3, 3, "F");
  ink(doc, THEME.white);
  doc.text(text, chipX + chipWidth / 2, y + chipHeight / 2 + 2.8, { align: "center" });
  resetTextStyle(doc);
  return chipWidth;
}

/** Two-column "Field / Value" table — used for Case Information,
 * Investigation Statistics, Timeline Summary, and the Conclusion's stat
 * block. Gray header per this sprint's typography split (section headings
 * stay blue; table headers are gray). */
export function keyValueTable(doc: jsPDF, startY: number, rows: Array<[string, string]>): void {
  autoTable(doc, {
    startY,
    theme: "grid",
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 10, cellPadding: 7, textColor: THEME.text, lineColor: THEME.border, lineWidth: 0.5 },
    headStyles: { fillColor: THEME.tableHeader, textColor: THEME.white, fontStyle: "bold" },
    head: [["Field", "Value"]],
    body: rows,
    columnStyles: { 0: { cellWidth: 190, fontStyle: "bold" } },
  });
}

/** Shared styling for the report's multi-row data tables (Bookmarked
 * Events, Event Notes, Suspicious Events): alternating row color, gray
 * header, consistent border/padding — this sprint's "Better Tables"
 * requirement applied once here instead of per call site. Callers still
 * supply `head`/`body`/`columnStyles`/`didParseCell`/`didDrawCell`. */
export function dataTable(doc: jsPDF, options: UserOptions): void {
  autoTable(doc, {
    theme: "striped",
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 9, cellPadding: 6, overflow: "linebreak", lineColor: THEME.border, lineWidth: 0.5 },
    headStyles: { fillColor: THEME.tableHeader, textColor: THEME.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: THEME.rowStripe },
    ...options,
  });
}

/** Blanks a cell's default text (for `didParseCell`) so a badge painted in
 * the matching `didDrawCell` hook doesn't render underneath duplicate
 * black text. Only affects body cells for the given column index. */
export function blankCellText(data: CellHookData, columnIndex: number): void {
  if (data.section === "body" && data.column.index === columnIndex) {
    data.cell.text = [""];
  }
}

/** Paints a colored badge chip centered inside a table cell — pair with
 * `blankCellText` in `didParseCell` for the same column so the chip is the
 * only thing rendered in that cell. `colorFor` resolves the cell's raw
 * (pre-blanked) value to a color, falling back to `THEME.muted` for any
 * value without an explicit mapping. */
export function drawCellBadge(
  doc: jsPDF,
  data: CellHookData,
  columnIndex: number,
  colorFor: (rawValue: string) => RgbColor | undefined,
): void {
  if (data.section !== "body" || data.column.index !== columnIndex) return;
  const text = String(data.cell.raw ?? "");
  const color = colorFor(text) ?? THEME.muted;
  const cx = data.cell.x + data.cell.width / 2;
  const cy = data.cell.y + data.cell.height / 2 - 7.5;
  drawBadgeChip(doc, text, cx, cy, color, "center");
}

/** Starts a new page (returning the fresh content-start y) if drawing
 * `needed` more points of content would run past the footer — keeps
 * freeform text sections (Executive Summary, Notes, Conclusion) from
 * splitting a subsection heading from its body across a page break.
 * Table-based sections don't need this: jspdf-autotable paginates itself. */
export function guardPageBreak(doc: jsPDF, y: number, needed: number): number {
  const { height } = pageSize(doc);
  if (y + needed > height - 70) {
    doc.addPage();
    return CONTENT_START_Y;
  }
  return y;
}

/**
 * Derives events/day and events/hour from a raw millisecond duration.
 * `report.ts` only exposes pre-formatted duration *strings* (by design —
 * presentation code shouldn't need raw numbers), so this sprint's caller
 * (`GenerateReportButton.tsx`) separately calls the same
 * `calculateStatistics` utility `report.ts` already uses internally to get
 * the two raw timestamps, and passes the millisecond span through here.
 * Never modifies `report.ts` itself. Returns "N/A" for zero/negative/
 * unavailable spans rather than dividing by zero.
 */
export function computeEventRates(
  totalEvents: number,
  durationMs: number | null,
): { perDay: string; perHour: string } {
  if (durationMs === null || durationMs <= 0 || totalEvents <= 0) {
    return { perDay: "N/A", perHour: "N/A" };
  }
  const hours = durationMs / (1000 * 60 * 60);
  const perHour = totalEvents / hours;
  const perDay = perHour * 24;
  const format = (value: number): string => (value < 1 ? value.toFixed(2) : value.toLocaleString(undefined, { maximumFractionDigits: 1 }));
  return { perDay: format(perDay), perHour: format(perHour) };
}
