/**
 * Pure, presentation-agnostic multi-file merge logic for the Multi-EVTX
 * Investigation feature (Phase 5.7). No React, no Zustand, no parsing —
 * every export here is a plain function over already-parsed `EvtxEvent[]`
 * results, following the same "pure lib module" contract as
 * `lib/statistics.ts` / `lib/eventFilters.ts` / `lib/timeline.ts`.
 *
 * This module deliberately does NOT call `parseEVTX` itself — the caller
 * (`evidenceStore.ts`) is responsible for calling the existing, unmodified
 * parser once per file and handing the results here to be tagged, merged,
 * sorted, and summarized. Keeping parsing and merging separate is what lets
 * each file be parsed fully independently (per the ticket's "Parse each
 * file independently" / "Parse files independently" requirements), with
 * merging as a distinct, easily-tested second step.
 */
import type { EvtxEvent, UploadedFileMeta } from "@/types/evidence";

export interface ParsedFileResult {
  meta: UploadedFileMeta;
  events: EvtxEvent[];
}

/**
 * Returns a new array of events, each tagged with `sourceFile`. Never
 * mutates the input array or its elements — `record-mapper.ts` (the
 * protected parser core) hands back plain objects with no `sourceFile`
 * field, and this is the one place that field gets populated, via a fresh
 * shallow copy per event rather than reassigning a shared object.
 */
export function tagEventsWithSource(events: readonly EvtxEvent[], sourceFile: string): EvtxEvent[] {
  return events.map((event) => ({ ...event, sourceFile }));
}

/**
 * Sort key for chronological merge: unparseable/missing timestamps sort to
 * the end rather than colliding at epoch 0, mirroring the same
 * "corrupt timestamp still evidence, never a fabricated date" principle
 * `record-mapper.ts#safeTimestamp` and `lib/detection/utils.ts#sortByTimestamp`
 * already follow elsewhere in this codebase.
 */
function timestampSortKey(event: EvtxEvent): number {
  if (!event.timestamp) return Number.POSITIVE_INFINITY;
  const ms = Date.parse(event.timestamp);
  return Number.isNaN(ms) ? Number.POSITIVE_INFINITY : ms;
}

/**
 * Tags every file's events with their source filename, concatenates all
 * files' events, and sorts the combined array chronologically in a single
 * `Array.prototype.sort` pass. `Array.prototype.sort` is a stable sort in
 * every JS engine this app targets (ES2019+), so events that tie on
 * timestamp (including same-file corrupt-timestamp events) keep their
 * original per-file relative order rather than being shuffled.
 *
 * ID collision safety: `EvtxEvent.id` is generated by the protected parser
 * core as `evt-${recordNum}` (see `record-mapper.ts`), which is guaranteed
 * unique only *within* one file — two independently-parsed EVTX files can
 * both contain a record number 1, and Windows Event Log record numbers
 * reset per-channel, so this is a real, expected case, not a hypothetical
 * one. Every other subsystem (notes, bookmarks, IOC findings, the Event
 * Details Drawer's selection) keys off `EvtxEvent.id` and assumes it is
 * unique across the whole loaded case, so a collision would silently merge
 * two unrelated events' notes/bookmarks/findings into one.
 *
 * When merging exactly one file, IDs are left completely untouched —
 * single-file investigations are byte-identical to this feature not
 * existing, so any notes/bookmarks a user already saved under the old
 * (pre-5.7) `evt-N` id format for a single-file case keep matching.
 *
 * When merging two or more files, every ID is namespaced with its file's
 * index (`f{fileIndex}:evt-N`) before the merge, guaranteeing uniqueness
 * across files while staying stable and deterministic for a given upload
 * order — this only changes ID shape for genuinely new multi-file cases,
 * which have no pre-existing single-file notes/bookmarks to preserve.
 */
export function mergeAndSortEvents(results: readonly ParsedFileResult[]): EvtxEvent[] {
  const needsNamespacing = results.length > 1;
  const merged: EvtxEvent[] = [];

  results.forEach((result, fileIndex) => {
    const tagged = tagEventsWithSource(result.events, result.meta.name);
    if (needsNamespacing) {
      for (const event of tagged) {
        event.id = `f${fileIndex}:${event.id}`;
      }
    }
    merged.push(...tagged);
  });

  merged.sort((a, b) => timestampSortKey(a) - timestampSortKey(b));
  return merged;
}

/**
 * Collapses the per-file `UploadedFileMeta[]` list into the single
 * `UploadedFileMeta` shape `evidenceStore.uploadedFile` has always exposed
 * (used as the notes/bookmarks case-namespacing key, the Report cover's
 * "Case Filename", `CaseStateGate`'s page description, and the Navbar file
 * badge — see those files, all unmodified in their own read of this
 * value). For a single file this is just that file's own meta, so
 * single-file behavior is byte-identical to before this phase. For
 * multiple files it synthesizes one summary record rather than requiring
 * every existing single-file consumer to be rewritten for an array.
 */
export function synthesizeUploadedFileMeta(
  files: readonly UploadedFileMeta[],
): UploadedFileMeta | null {
  if (files.length === 0) return null;
  if (files.length === 1) return files[0];

  const sizeBytes = files.reduce((sum, file) => sum + file.sizeBytes, 0);
  const uploadedAt = files.reduce(
    (latest, file) => (file.uploadedAt > latest ? file.uploadedAt : latest),
    files[0].uploadedAt,
  );
  const name =
    files.length <= 3
      ? files.map((file) => file.name).join(", ")
      : `${files.length} EVTX files merged`;

  return { name, sizeBytes, uploadedAt };
}

/**
 * QA-01 — Duplicate EVTX File Protection. Cheap, browser-native identity
 * for detecting an accidentally-reselected file within one upload batch:
 * filename + size + `lastModified`, all read directly off the `File`
 * object with no content access. Deliberately does NOT hash file
 * contents — for the "same file selected twice" case this identity triple
 * is already exactly what the OS/file picker itself would consider "the
 * same file", and hashing every file (potentially hundreds of MB, per
 * SDD §7's large-file target) on every upload would cost real time for a
 * check that, in the common case, this cheaper identity already answers
 * correctly. Two different files that happen to share only a name (e.g.
 * two unrelated hosts' exports both called "Security.evtx") will not
 * collide here, since their size and/or `lastModified` will essentially
 * always differ.
 */
function fileIdentityKey(file: File): string {
  return `${file.name}::${file.size}::${file.lastModified}`;
}

export interface DedupeFilesResult {
  /** First occurrence of each distinct identity, in original order. */
  uniqueFiles: File[];
  /** Names of files skipped because an earlier file in the same batch
   * already had an identical identity — in encounter order. May contain
   * the same name more than once if the same file was selected 3+ times. */
  duplicateFiles: string[];
}

/**
 * Removes exact-identity repeats from one upload batch, keeping the FIRST
 * occurrence of each identity. Never mutates `files`. This is the single
 * place duplicate detection happens — `evidenceStore.ts#loadFiles` calls
 * this before any file is handed to the parser, so a duplicate is never
 * parsed and never merged as a second evidence source (see that module's
 * own doc comment on this call).
 */
export function dedupeFiles(files: readonly File[]): DedupeFilesResult {
  const seen = new Set<string>();
  const uniqueFiles: File[] = [];
  const duplicateFiles: string[] = [];

  for (const file of files) {
    const key = fileIdentityKey(file);
    if (seen.has(key)) {
      duplicateFiles.push(file.name);
    } else {
      seen.add(key);
      uniqueFiles.push(file);
    }
  }

  return { uniqueFiles, duplicateFiles };
}

/** Matches `record-mapper.ts#xmlToEvent`'s own fallback value for a record
 * whose XML has no `<Computer>` element — treated as "no host information",
 * never as a real, comparable host identity (see `checkHostConsistency`). */
const UNKNOWN_HOST = "Unknown";

export interface HostConsistencyResult {
  /** True when every file's events agree on a host (or too little host
   * information exists to say otherwise) — the common, expected case. */
  isConsistent: boolean;
  /** Every distinct *known* (non-"Unknown") host observed across all
   * files, sorted. Length 0 or 1 whenever `isConsistent` is true. */
  hosts: string[];
}

/**
 * QA-02 — Same-Host Advisory. Cross-file host/computer consistency check,
 * advisory only — this never blocks or alters a load, it only reports
 * what it found so the caller (`evidenceStore.ts`) can surface a warning.
 * Only meaningful across more than one file; call sites should skip this
 * for a single-file load (see `evidenceStore.ts`).
 *
 * "Unknown" is deliberately excluded from the comparison: a file whose
 * records carry no `<Computer>` element must never be treated as "a
 * different host" than one that does — that would falsely warn on
 * genuinely missing metadata rather than a real host mismatch, which is
 * exactly the failure mode this function's callers are required to avoid.
 * A file contributes nothing to `hosts` unless at least one of its events
 * has real, known host information.
 */
export function checkHostConsistency(results: readonly ParsedFileResult[]): HostConsistencyResult {
  if (results.length <= 1) return { isConsistent: true, hosts: [] };

  const hostSet = new Set<string>();
  for (const result of results) {
    for (const event of result.events) {
      if (event.computer && event.computer !== UNKNOWN_HOST) {
        hostSet.add(event.computer);
      }
    }
  }

  const hosts = [...hostSet].sort();
  return { isConsistent: hosts.length <= 1, hosts };
}

export interface PerFileStatistics {
  fileName: string;
  sizeBytes: number;
  eventCount: number;
  /** null when this file contributed no events with a parseable timestamp. */
  earliestTimestamp: Date | null;
  /** null when this file contributed no events with a parseable timestamp. */
  latestTimestamp: Date | null;
}

/**
 * Per-file breakdown of the merged event set — powers the Dashboard's
 * "Files Loaded" detail and the Report's new per-file statistics rows.
 * Single pass over `events` to bucket by `sourceFile`, then one pass per
 * file (bounded by file count, not event count) to compute each bucket's
 * own earliest/latest — same two-tier aggregation shape as
 * `lib/analytics/aggregation.ts`'s single-pass-then-cheap-derivation
 * pattern, just scoped to per-file counts rather than per-provider ones.
 */
export function computePerFileStatistics(
  events: readonly EvtxEvent[],
  files: readonly UploadedFileMeta[],
): PerFileStatistics[] {
  const bucketsByFile = new Map<string, EvtxEvent[]>();
  for (const event of events) {
    const key = event.sourceFile ?? "Unknown";
    const bucket = bucketsByFile.get(key);
    if (bucket) bucket.push(event);
    else bucketsByFile.set(key, [event]);
  }

  return files.map((file) => {
    const bucket = bucketsByFile.get(file.name) ?? [];
    let earliestMs: number | null = null;
    let latestMs: number | null = null;
    for (const event of bucket) {
      if (!event.timestamp) continue;
      const ms = Date.parse(event.timestamp);
      if (Number.isNaN(ms)) continue;
      if (earliestMs === null || ms < earliestMs) earliestMs = ms;
      if (latestMs === null || ms > latestMs) latestMs = ms;
    }
    return {
      fileName: file.name,
      sizeBytes: file.sizeBytes,
      eventCount: bucket.length,
      earliestTimestamp: earliestMs === null ? null : new Date(earliestMs),
      latestTimestamp: latestMs === null ? null : new Date(latestMs),
    };
  });
}
